version: '3.8'
services:
  api:
    build: ./api
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    build: ./db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: ./web
    ports:
      - '80:3000'
    depends_on:
      - api

volumes:
  dbdata:
